### ISSUE TITLE
如何分享到Mixin

### ISSUE THREAD

**Issue by zhdhr0000** [MixinMessenger/android-app#49]
我们的产品非常喜欢Mixin，他对我们提出了分享到Mixin的一个需求
请问Mixin现在是否支持？

**Comment by crossle** [comment]
分享什么到 Mixin ？Mixin 支持 Android 系统的分享功能

**Comment by zhdhr0000** [comment]
就是类似于分享到微信，分享到微博那样的，对于App的定向分享，不通过Android系统分享的方式
目前是分享看到的新闻，包含一个标题和一个URL

**Comment by crossle** [comment]
那就支持，直接唤起 https://github.com/MixinMessenger/android-app/blob/master/app/src/main/AndroidManifest.xml#L92

**Comment by zhdhr0000** [comment]
ok，我尝试一下，谢谢
