### ISSUE TITLE
ShareHelper非单例

### ISSUE THREAD

**Issue by zhdhr0000** [MixinMessenger/android-app#52]
ShareHelper companion object 的get方法拿到的ShareHelper非单例
不太清楚你们是否接受非开发团队成员的pr
所以提一个issue.

问题明细:
one.mixin.android.util包下的ShareHelper.kt文件

        private var INSTANCE: ShareHelper? = null
        fun get(): ShareHelper =
            INSTANCE ?: synchronized(this) {
                INSTANCE ?: ShareHelper()
            }

get()方法没有对INSTANCE赋值，每次都会创建一个新的ShareHelper出来,建议改为:

        private var INSTANCE: ShareHelper? = null
        fun get(): ShareHelper =
            INSTANCE ?: synchronized(this) {
                INSTANCE ?: ShareHelper().also { INSTANCE = it }
            }

**Comment by crossle** [comment]
果然是个问题，欢迎👏 PR

**Comment by zhdhr0000** [comment]
已提pr 😄
