### ISSUE TITLE
[bug]刚在P1群里看到的，转一下

### ISSUE THREAD

**Issue by pphaolu** [MixinMessenger/android-app#57]
刚在P1群里看到的，转一下
![qq 20180606175615](https://user-images.githubusercontent.com/35622701/41031359-03171f24-69b3-11e8-82b2-9f2124572fd1.png)

**Comment by pphaolu** [comment]
![qq 20180606175759](https://user-images.githubusercontent.com/35622701/41031428-2c0c9f12-69b3-11e8-9737-d7caf5815e74.png)

**Comment by pphaolu** [comment]
抱歉，应该发在IOS区
刚问了下 ，用的是 ip6 ,ios 11.3.1
复制了一个mixin id

**Comment by cedricfung** [comment]
不要用中国区 App Store ID 就没问题了
